{% set name = "safe-pysha3" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/5afe/pysha3/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0398e0b98573d93c81318073c2d2c2426a6d02b4bca85ef483c4276bdda3378c
  patches:
    - fix-py3.12-removed-failIf.patch
    - fix-pypy-rebuild-backport.inc.patch

build:
  script: {{ PYTHON }} -m pip install . -vvv
  number: 2
  skip: true  # [py==38]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - sha3
  source_files:
    - tests.py
    - vectors/
  commands:
    - pip check
    - python tests.py
  requires:
    - pip

about:
  home: https://github.com/5afe/pysha3
  summary: SHA-3 (Keccak) for Python 3.9 - 3.11
  license: PDDL-1.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MementoRC
