{% set name = "safe-pysha3" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/5afe/pysha3/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 27cfcf535169e05f839d1f1e6fdf69fdde1164f8f4712c02c1c43dd88ee6b6d2
  patches:
    - fix-py3.12-removed-failIf.patch
    - fix-pypy-rebuild-backport.inc.patch
    - fix-pypy-hashlib-not-ro.patch

build:
  script: {{ PYTHON }} -m pip install . -vvv
  number: 0
  skip: true  # [py==38]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - python  # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - sha3
  source_files:   # [py<313]
    - tests.py  # [py<313]
    - vectors/  # [py<313]
  commands:
    - pip check
    - python tests.py  # [py<313]
  requires:
    - pip
    - python

about:
  home: https://github.com/5afe/pysha3
  summary: SHA-3 (Keccak) for Python 3.9 - 3.11
  license: PDDL-1.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MementoRC
